export const strings = {
  common: {
    add: 'Dodaj',
    save: 'Zapisz',
    cancel: 'Anuluj',
    delete: 'Usuń',
    close: 'Zamknij',
    confirmDeletePlain: 'Usunąć zadanie na stałe?',
    appError: 'Coś poszło nie tak.',
    retry: 'Spróbuj ponownie',
  },
  tabs: { today: 'Dziś', master: 'Lista główna', calendar: 'Kalendarz', settings: 'Ustawienia' },
  quickAdd: {
    title: 'Nowe zadanie',
    titlePlaceholder: 'Co jest do zrobienia?',
    priorityPrompt: 'Jak pilne?',
    priorityA: 'A — dziś/jutro',
    priorityB: 'B — częściowo pilne',
    priorityC: 'C — może poczekać',
  },
  dailyList: {
    earlierDays: 'z wcześniejszych dni',
    doneToday: 'Zrobione dziś',
    emptyState: 'Pusto? Spokojnie — dodaj zadanie albo przełóż coś z listy głównej.',
    moveToTomorrow: 'Przełóż na jutro',
    sectionA: 'A — najważniejsze',
    sectionB: 'B — mniej pilne',
    sectionC: 'C — na później',
    sectionNameA: 'Najważniejsze',
    sectionNameB: 'Mniej pilne',
    sectionNameC: 'Na później',
    moveShort: '→ jutro',
    // "Zrobione dziś · Pranie, Kot" — a dot after the label, commas between titles
    doneSeparator: ' · ',
    doneListSeparator: ', ',
    addTask: 'Dodaj zadanie',
    taskCountForms: { one: 'zadanie', few: 'zadania', many: 'zadań' },
    markDone: 'oznacz jako zrobione',
    undoDone: 'cofnij',
  },
  review: { title: 'Przegląd dnia', problemFormEntry: 'Problem w 5 krokach' },
  calendar: {
    addEvent: 'Dodaj wydarzenie',
    editEvent: 'Edytuj wydarzenie',
    eventTitlePlaceholder: 'Np. wizyta u lekarza',
    eventNotePlaceholder: 'Notatka (opcjonalnie)',
    note: 'Notatka',
    confirmDeleteEvent: 'Usunąć to wydarzenie na stałe?',
    emptyDay: 'Nic w kalendarzu. To też jest informacja.',
    restFree: 'Reszta dnia jest wolna.',
    until: (time: string) => `do ${time}`,
    start: 'Start',
    end: 'Koniec',
    prevWeek: 'Poprzedni tydzień',
    nextWeek: 'Następny tydzień',
  },
  editor: {
    day: 'Dzień',
    time: 'Godzina',
    breakDown: 'Podziel na kroki',
    category: 'Kategoria',
    categoryPlaceholder: 'np. dom, praca',
    addedSince: 'Na liście od',
  },
  master: {
    oneStepHint: 'Na listę dzienną bierz jeden krok naraz.',
    historyLink: 'Historia',
  },
  breakdown: {
    action: 'Podziel na kroki',
    oneDayTest: 'Dasz radę zrobić ten krok w jeden dzień?',
    splitFurtherHint: 'Jeśli chcesz to odkładać — podziel na mniejsze.',
    stepPlaceholder: 'Krok…',
    noStepsHint: 'Wpisz przynajmniej jeden krok.',
    dateCleared: 'Zadanie stało się zbiorem kroków — jego data jest wyczyszczona.',
    confirmDelete: (n: number) => `Usunąć zadanie wraz z ${n} krokami?`,
  },
  problemForm: {
    title: 'Problem w 5 krokach',
    step1: 'Opisz problem w 1–2 zdaniach',
    step1Placeholder: 'Np. nie mogę się zdecydować…',
    step2: 'Wypisz wszystkie rozwiązania — bez oceniania',
    step2Placeholder: 'Rozwiązanie…',
    step3: 'Plusy i minusy każdego rozwiązania',
    proPlaceholder: '+',
    conPlaceholder: '−',
    step4: 'Oceń każde od 1 do 10',
    step5: 'Najlepiej oceniane — wdrażasz?',
    choose: 'Wybieram to',
    pickNext: 'Wolę kolejne najwyżej oceniane',
    addAsTask: 'Dodaj jako zadanie',
    next: 'Dalej',
  },
  history: { title: 'Historia', subtitle: 'Tyle się udało' },
  onboarding: {
    screen1: 'Dwa narzędzia: kalendarz (data i godzina) i lista zadań (bez daty).',
    screen2title: 'O której porze przejrzysz dzień? (np. przy porannej kawie)',
    screen2intro: 'Ustaw JEDNO przypomnienie systemowe:',
    screen2clock: 'Zegar: codzienny budzik o tej porze',
    screen2calendar: 'Kalendarz: codzienne wydarzenie z alertem',
    screen2shortcuts: 'Skróty: automatyzacja „o porze dnia” z akcją Otwórz aplikację → Plan Dnia (nie Otwórz URL — to otwiera Safari, z pustymi danymi)',
    screen3: 'Dodaj pierwsze zadanie. Kopię zapasową zrobisz później w Ustawieniach.',
    next: 'Dalej',
    start: 'Zaczynam',
  },
  settings: {
    title: 'Ustawienia',
    backupSection: 'Kopia zapasowa',
    backupHint: 'Eksportuj co jakiś czas — to Twoja historia pracy.',
    export: 'Eksportuj kopię (JSON)',
    import: 'Importuj kopię',
    confirmImport: 'Zastąpić wszystkie dane zawartością kopii?',
    imported: 'Wczytano kopię.',
    importError: 'Nie udało się wczytać pliku.',
    shareError: 'Nie udało się udostępnić — pobieram plik zamiast tego.',
    reviewTimeLabel: 'Twoja pora przeglądu',
    reminderHint: 'Przypomnienie ustawiasz w systemie: Zegar (budzik), Kalendarz (wydarzenie z alertem) albo Skróty (automatyzacja o porze dnia).',
    version: 'Wersja',
  },
  dates: {
    // Intl 'pl-PL' emits "pt" lowercase with a trailing dot in some runtimes and
    // a comma in the long form — neither matches the design, so the abbreviations
    // are spelled out here. Index by Date.getDay(): 0 = Sunday.
    weekdaysShort: ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
  },
} as const;
