// Downloads the Barlow / Barlow Condensed subsets we use and rewrites Google's
// @font-face CSS to point at our own origin. Dev-time only — run it by hand
// (`npm run fonts`) when the font set changes. The app itself never talks to a
// CDN; see CLAUDE.md ("no runtime network calls").
import fs from 'node:fs';
import path from 'node:path';

const API = 'https://fonts.googleapis.com/css2'
  + '?family=Barlow:wght@400;500;700'
  + '&family=Barlow+Condensed:wght@400;600'
  + '&display=swap';
// Google serves woff2 only to a browser-looking UA; anything else gets ttf.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
// Polish needs latin-ext (ł ż ś ę ą ć ń ó ź); vietnamese is dead weight here.
const SUBSETS = new Set(['latin', 'latin-ext']);

const outDir = path.resolve('public/fonts');
const cssOut = path.resolve('src/lib/design/fonts.css');

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();
fs.mkdirSync(outDir, { recursive: true });

const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
const kept = [];
let bytes = 0;

for (const [, subset, body] of blocks) {
  if (!SUBSETS.has(subset)) continue;
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();
  const url = /url\((https[^)]+)\)/.exec(body)[1];

  const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
  const data = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  fs.writeFileSync(path.join(outDir, file), data);
  bytes += data.length;
  console.log(`wrote public/fonts/${file} (${Math.round(data.length / 1024)} KB)`);

  kept.push(
    `/* ${subset} */\n@font-face {\n`
    + `  font-family: '${family}';\n`
    + `  font-style: normal;\n`
    + `  font-weight: ${weight};\n`
    + `  font-display: swap;\n`
    + `  src: url('/fonts/${file}') format('woff2');\n`
    + `  unicode-range: ${range};\n}`,
  );
}

const header = '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n'
  + '   Self-hosted so the app makes no runtime network calls. */\n\n';
fs.writeFileSync(cssOut, header + kept.join('\n\n') + '\n');
console.log(`wrote src/lib/design/fonts.css (${kept.length} faces, ${Math.round(bytes / 1024)} KB of woff2)`);

// Barlow is SIL OFL 1.1 — redistributing the files requires shipping the licence.
const LICENSE = 'https://raw.githubusercontent.com/google/fonts/main/ofl/barlow/OFL.txt';
fs.writeFileSync(path.join(outDir, 'OFL.txt'), await (await fetch(LICENSE)).text());
console.log('wrote public/fonts/OFL.txt');
